### ISSUE TITLE
leaderboard

### ISSUE THREAD

**Issue by diewland** [avawalk/avarun#4]

**Comment by chulasoft** [comment]
รูปแบบ คือเลือกประเทษ ของตัวเอง แล้วสะสมคะแนน เข้าประเทศตัวเอง ทำ leader board ทที่นำอยู่

**Comment by chulasoft** [comment]
การเก็บคะแนน
หลังจบเกม ให้เลือก ประเทศ หรือ Detect Auto ก็ได้ ส่วน นับ Score แบบ Accumulate ไปเรื่อยๆ

**Comment by diewland** [comment]
> การเก็บคะแนน หลังจบเกม ให้เลือก ประเทศ หรือ Detect Auto ก็ได้ ส่วน นับ Score แบบ Accumulate ไปเรื่อยๆ

add country combobox on bottom-right of game screen
<img width="293" alt="image" src="https://github.com/user-attachments/assets/35bd6052-0082-4fbc-9e8e-2bbe91f1a1a0">

**Comment by diewland** [comment]
https://github.com/avawalk/avarun/commit/f6a155cd7c0b9261175565d68852ee0a5f7b3f03
