### ISSUE TITLE
ใส่ลิ้งเพลง เข้าไปให้กดได้

### ISSUE THREAD

**Issue by chulasoft** [avawalk/avarun#6]
https://www.tiktok.com/@apecoftonderock/video/7443354895115226375

**Comment by diewland** [comment]
* add more menus (game, leaderboard)
* fix mobile UI, cannot choose country

**Comment by diewland** [comment]
> https://www.tiktok.com/@apecoftonderock/video/7443354895115226375

tiktok logo at top-right of screen ?

**Comment by chulasoft** [comment]
its okay in top-right of screen

**Comment by diewland** [comment]
https://github.com/avawalk/avarun/commit/f6a155cd7c0b9261175565d68852ee0a5f7b3f03
